FROM apache/airflow:2.9.2-python3.11

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    default-jdk \
    mafft \
    fasttree \
    muscle \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /opt/airflow/dags /opt/airflow/plugins /opt/airflow/config /opt/bio /opt/spark/jobs \
    && chown -R airflow:root /opt/bio /opt/spark

USER airflow

COPY airflow/requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY airflow/dags/ /opt/airflow/dags/
COPY airflow/plugins/ /opt/airflow/plugins/
COPY airflow/config/ /opt/airflow/config/
COPY bio/ /opt/bio/
COPY spark/jobs/ /opt/spark/jobs/